### ISSUE TITLE
Parameter specified as non-null is null

### ISSUE THREAD

**Issue by jamshed-ali-keela** [rkumar0206/ManageYourRenters#108]
Build file 'C:\Users\jamsh\AndroidStudioProjects\ManageYourRenters\app\build.gradle' line: 43

A problem occurred evaluating project ':app'.
> Parameter specified as non-null is null: method com.android.build.gradle.internal.dsl.BaseFlavor.buildConfigField, parameter value

**Comment by rkumar0206** [comment]
Add any dummy String in local.properties file with key MANAGE_YOUR_RENTERS_BASE_URL
Example: MANAGE_YOUR_RENTERS_BASE_URL="ANY_DUMMY_STRING"

This string is not used anywhere in the app yet so it won't be a problem.
